//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpontimeCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessages
    {
        public int Id { get; set; }
        public string MessageOwnerId { get; set; }
        public int EventId { get; set; }
        public System.DateTime PostDate { get; set; }
        public string Text { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Events Events { get; set; }
    }
}
