//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpontimeCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInvite
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string FriendId { get; set; }
        public int EventInviteStatus { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Events Events { get; set; }
    }
}
