//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpontimeCore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class spontimeDatabaseEntities : DbContext
    {
        public spontimeDatabaseEntities()
            : base("name=spontimeDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ChatMessages> ChatMessages { get; set; }
        public virtual DbSet<EventInvite> EventInvite { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<FriendInvites> FriendInvites { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
    }
}
